[runner]
module = "streamlit"

[logger]
level = "info"

[theme]
primaryColor = "#6366F1"
backgroundColor = "#080b14"
secondaryBackgroundColor = "#0b0f1a"
textColor = "#f8fafc"

[mapbox]
token = ""

[markdown]
enableExtensions = true
